CodingKatz/CodingKatz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

app_name="CodingKatz"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.LogReg.urls', namespace="LogReg")),
    url(r'^', include('apps.Wall.urls', namespace="Wall")),
    url(r'^', include('apps.User.urls', namespace="User")),
]

CodingKatz/apps/LogReg/urls.py
from django.conf.urls import url
from . import views

app_name="LogReg"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    # url(r'^1$', views.index1, name="index1"),
    # url(r'^2$', views.index2, name="index2"),
    # url(r'^3$', views.index3, name="index3"),
    url(r'^login', views.log_reg, name="login"),
    url(r'^register', views.log_reg, name="register"),
    url(r'^logout', views.logout, name="logout"),
]

CodingKatz/apps/User/urls.py
from django.conf.urls import url
from . import views

app_name="User"

urlpatterns = [
    url(r'^profile', views.profile, name="profile"),
    url(r'^edit', views.edit, name="edit"),
    url(r'^delete', views.delete, name="delete"),
    url(r'^note/(?P<user_id>\d+)/$', views.note, name="note"),
    url(r'^userComment/(?P<user_id>\d+)/(?P<message_id>\d+)*$', views.comment, name='userComment'),
    url(r'^userDeleteMessage/(?P<user_id>\d+)/(?P<message_id>\d+)/$', views.deleteMessage, name="userDeleteMessage"),
    url(r'^userDeleteComment/(?P<user_id>\d+)/(?P<comment_id>\d+)/$', views.deleteComment, name="userDeleteComment"),
    url(r'^users/show/(?P<user_id>\d+)/$', views.show_user, name='show_user'),
]

CodingKatz/apps/Wall/urls.py
from django.conf.urls import url
from . import views

app_name="Wall"

urlpatterns = [
    url(r'^wall', views.wall, name="wall"),
    url(r'^message', views.message, name="message"),
    url(r'^comment/(?P<message_id>\d+)*$', views.comment, name='comment'),
    url(r'^deleteMessage/(?P<message_id>\d+)/$', views.deleteMessage, name="deleteMessage"),
    url(r'^deleteComment/(?P<comment_id>\d+)/$', views.deleteComment, name="deleteComment"),
    # url(r'^users/show/(?P<user_id>\d+)/$', views.show_user, name='show_user'),
]

CodingKatz/apps/User/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..LogReg.models import userDB
# Create your models here.

class noteManager(models.Manager):
    def note_check(self, data, author, user_id):
        errors = []
        if len(data['note'])  < 1:
            errors.append(['note', 'Note must be entered.'])

        if errors:
            return [False, errors]
        else:
            recipient = userDB.objects.get(id = user_id)
            newNote = Note.objects.create(note=data['note'], author=author, recipient=recipient)
            return [True]

class Note(models.Model):
    note = models.TextField()
    author = models.ForeignKey(userDB, related_name='note_author', on_delete=models.PROTECT)
    recipient = models.ForeignKey(userDB, related_name='note_recipient', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = noteManager()

CodingKatz/apps/Wall/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..LogReg.models import userDB

# Create your models here.
class messageManager(models.Manager):
    def message_check(self, data, author):
        errors = []
        if len(data['message']) < 1:
            errors.append(['message', 'Message must be entered.'])

        if errors:
            return [False, errors]
        else:
            #author will be in session and can be passed in from views
            #owner_id will be passed into the url
            newMessage = Message.objects.create(message=data['message'], author=author)
            return [True]

class commentManager(models.Manager):
    def comment_check(self, data, author, message_id):
        errors = []
        if len(data['comment']) < 1:
            errors.append(['comment', 'Comment must be entered.'])

        if errors:
            return [False, errors]
        else:
            #author will be in session and can be passed in
            #message_id will be passed into the url
            message = Message.objects.get(id=message_id)
            newComment = Comment.objects.create(comment=data['comment'], author=author, message=message)
            return [True]

class Message(models.Model):
    message = models.TextField()
    author = models.ForeignKey(userDB, related_name='message_author', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = messageManager()

class Comment(models.Model):
    comment = models.TextField()
    message = models.ForeignKey(Message, related_name='comment_message', on_delete=models.PROTECT)
    author = models.ForeignKey(userDB, related_name='comment_author', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = commentManager()

CodingKatz/apps/User/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from itertools import chain
from operator import attrgetter
from ..LogReg.models import userDB
from ..Wall.models import Message, Comment
from .models import Note

def profile(request):
    #Confirm user id is logged in to view that page
    if "user" in request.session:
    #User information in session and can be displayed on the page through the template
        context = {
            'user': userDB.objects.get(id=request.session['user']['id']),
        }
    #Display user page
        return render(request, 'User/profile.html', context)
    return redirect('LogReg:index')

#validates information and updates user accordingly
def edit(request):
    print(request)
    #Content from edit form
    if request.method == 'POST':
    #Validate content from form
        response = userDB.objects.check_info_edit(request.POST, request.session['user']['id'])
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
        #Update session user
        request.session['user'] = {
            "first_name": response[1].first_name,
            "last_name": response[1].last_name,
            "id": response[1].id,
        }
    #Redirect user to user profile page
    return redirect('User:profile')

def delete(request):
    #Confirm user wants to delete their account

    #Consider whether to Cascade delete user's information, messages, and comments from the database

    #Potential for 'recover account' for users which will bring back all their data

    #Return former user to landing page
    return redirect('LogReg:index')

def note(request, user_id):
    #Content from message
    #Validate content
    #Put message in database
    #Return message to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Note.objects.note_check(request.POST, author, user_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags='message')
    user = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=user).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=user).order_by('id').reverse()

    all_user_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': user,
        'all_correspondence': all_user_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

def comment(request, message_id, user_id):
    #Content from comment
    #Validate content
    #Put comment in database
    #Return comment to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Comment.objects.comment_check(request.POST, author, message_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags = message_id)
    user = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=user).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=user).order_by('id').reverse()

    all_user_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': user,
        'all_correspondence': all_user_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

def deleteMessage(request, message_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete message from database

    #Return user to page through redirect
    return redirect('User:user')

def deleteComment(request, comment_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete comment from database

    #Return user to page through redirect
    return redirect('User:user')

#display user page with their messages and comments
def show_user(request, user_id):
    recipient = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=recipient).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=recipient).order_by('id').reverse()

    all_recipient_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': recipient,
        'all_correspondence': all_recipient_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

# Create your views here.

CodingKatz/apps/Wall/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from ..LogReg.models import userDB
from .models import Message, Comment

def wall(request):
    #Retrieve all messages and comments related to user in session and put in context
    #Render wall template
    if "user" in request.session:
        author = userDB.objects.get(id=request.session['user']['id'])
        context = {
            'user': author,
            'all_messages': Message.objects.all().order_by('id').reverse(),
            'comments': Comment.objects.all().order_by('id')
        }
        return render(request, 'Wall/wall.html', context)
    return redirect('LogReg:index')

def message(request):
    #Content from message
    #Validate content
    #Put message in database
    #Return message to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Message.objects.message_check(request.POST, author)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags='message')
    return redirect('Wall:wall')

def comment(request, message_id):
    #Content from comment
    #Validate content
    #Put comment in database
    #Return comment to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Comment.objects.comment_check(request.POST, author, message_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags = message_id)
    return redirect('Wall:wall')

def deleteMessage(request, message_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete message from database

    #Return user to page through redirect
    return redirect('Wall:wall')

def deleteComment(request, comment_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete comment from database

    #Return user to page through redirect
    return redirect('Wall:wall')

#display user page with their messages and comments
# def show_user(request, user_id):
#     author = userDB.objects.get(id = user_id)
#     context = {
#         'user': author,
#         'all_messages': Message.objects.filter(author=author).order_by('id').reverse(),
#         'comments': Comment.objects.all().order_by('id')
#     }
#     return render(request, 'Wall/user.html', context)



# Create your views here.

CodingKatz/apps/Wall/templates/Wall/user.html
<!DOCTYPE html>
<html>
{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  <!-- css stylesheets -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  <link rel="stylesheet" href="{% static 'wall/css/style.css' %}">
  <title>{{ user.first_name }}'s Wall</title>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="navbar-form navbar-right">
          <li><a href="{% url 'Wall:wall' %}">The Wall</a></li>
          <li><a href="{% url 'User:profile' %}">Profile</a></li>
          <li><a href="{% url 'LogReg:logout' %}">Logout</a></li>
        </ul>
      </div>
      <!--/.navbar-collapse -->
    </div>
  </nav>

  <div class="row">
    <header class="jumbotron jumboText">
      <div class="container">
        <div class="textOverImg col-md-4">
          <h2>{{user.first_name}} {{user.last_name}}</h2>
          <h4>
                  Member Since:
                  <!-- time is showing 3 hours ahead but this fix does not work -->
                  {% load tz %}
                  {% localtime on %}
                  {{user.created_at}}
                  {% endlocaltime %}
                </h4>
        </div>
      </div>
    </header>
  </div>

  <div id="main" class="container">

    <div id="post" class="row">
      <!-- user info then messages-->
      <div class="col-md-12">
        <h2>Leave a message for {{user.first_name}}</h2>
        <div class="flash_messages">
          {% if messages %}
          {% for message in messages%}
          <p class="error">{{ message }}</p>
          {% endfor %}
          {% endif %}
        </div>
        <form action="{% url 'Wall:message' %}" method="post">
          {% csrf_token %}
          <fieldset>
            <textarea name="message" rows="4" cols="90" placeholder="Write your message here"></textarea>
            <button class="btn btn-primary btn-block submit" name="button" value="message_submit" type="submit">Submit</button>
          </fieldset>
        </form>
      </div>
    </div>

    <div class="row">
      <div id="messages" class="col-md-12">
        {% for message in all_messages %}
        <h5><a href="{% url 'Wall:show_user' message.author.id %}">{{message.author.first_name}} {{message.author.last_name}}</a>  - {{message.created_at|timesince}} ago</h5>
        <p class="message">{{ message.message }}</p>



        {% for comment in comments %}
        <div id="comments" class="toggle col-md-12">
          {% if message.id == comment.message.id %}
          <ul>
            <h5><a href="{% url 'Wall:show_user' comment.author.id %}">{{comment.author.first_name}} {{comment.author.last_name}}</a> - {{comment.created_at|timesince}} ago</h5>
            <li>{{ comment.comment }}</li>
          </ul>
          {% endif %}
        </div>
        {% endfor %}
        <div class="flash_messages">
          {% if messages %}
          {% for message in messages %}
          <p class="error">{{message}}</p>
          {% endfor %}
          {% endif %}
        </div>
          <h6 class="comment_label">Post a comment</h6>
          <form action="{% url 'Wall:comment' message_id=message.id %}" method="post">
            {% csrf_token %}
            {% if messages %}
            {% for message in messages%}
            <p class="error">{{ message }}</p>
            {% endfor %}
            {% endif %}
            <div class="form-group">
              <textarea name="comment" rows="1" cols="60" placeholder="Write your comment here"></textarea>
            </div>
            <button class="btn btn-sm btn-primary submit" name="wall_posts" value="comment_submit" type="submit">Submit</button>
          </form>
          {% endfor %}
        </div>
    </div>
  </div>
</body>

</html>

CodingKatz/apps/Wall/templates/Wall/wall.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- css stylesheets -->
  <link rel="stylesheet" href="{% static 'wall/css/style.css' %}">

  <title>The Wall</title>
</head>

<body class="grid">
  <div class="overlay"></div>
  <header class="header">
    <nav class="navbar">
          <ul class="top-nav">
            <li class="top-nav__item"><a href="{% url 'User:show_user' user.id %}" class="top-nav__link">My wall</a></li>
            <li class="top-nav__item"><a href="{% url 'User:profile' %}" class="top-nav__link">Edit Profile</a></li>
            <li class="top-nav__item"><a href="{% url 'LogReg:logout' %}" class="top-nav__link">Logout</a></li>
          </ul>
    </nav>
    <div class="header__greeting">
      <h1>The Wall{% if "user" in request.session %} - Hello {{ request.session.user.first_name }} {% endif %}</h1>
    </div>
  </header>

  <section id="main" class="content">

    <div id="post" class="form">
      <form action="{% url 'Wall:message' %}" method="post" class="form-message">
        {% csrf_token %}
        <fieldset>
          <div class="form-group">
            <label class="flash_messages"><h2>Post a message</h2>
              {% if messages %}
              {% for message in messages %}
              {% if message.extra_tags == 'message' %}
              <p class="error">{{ message }}</p>
              {% endif %}
              {% endfor %}
              {% endif %}
            </label>
          </div>
          <div class="form-group">
            <textarea rows="4" name="message" class="message-input"></textarea>
            <button class="btn btn--green submit" name="wall_posts" value="message_submit" type="submit">Submit</button>
          </div>
        </fieldset>
      </form>
    </div>

      <div class="messages">
        <!-- MESSAGE-GROUP -->
        {% if all_messages %}
        {% for message in all_messages %}
        <div class="message-group">
          <!-- MAIN MESSAGE SECTION -->
          <h5><a href="{% url 'User:show_user' message.author.id %}" class="messages__link">{{message.author.first_name}} {{message.author.last_name}}</a>  - {{message.created_at|timesince}} ago</h5>
          <p class="message">{{ message.message }}</p>
          <!-- END MAIN MESSAGE SECTION -->

          <div class="comments">
          <!-- SINGLE COMMENT SECTION -->
            <div class="comment">
              {% if comments %}
              <ul>
                {% for comment in comments %} {% if message.id == comment.message.id %}
                <li>
                  <h5>
                    <a href="{% url 'User:show_user' comment.author.id %}" class="comments__link">{{comment.author.first_name}} {{comment.author.last_name}}</a> - {{comment.created_at|timesince}} ago</h5>
                  {{ comment.comment }}</li>
                {% endif %} {% endfor %}
              </ul>
              {% endif %}
            </div>
            <!-- END SINGLE COMMENT SECTION -->
          <!-- COMMENT FORM -->
          <div class="comment-form">
            <h6 class="comment_label">Post a comment</h6>
            <form action="{% url 'Wall:comment' message_id=message.id %}" method="post">
              {% csrf_token %}
              <!-- CREATE ANCHOR TAGS SO WHEN PAGE REFRESHES WITH ERROR OR NEW COMMENT PAGE LOADS TO SHOW ERROR OR NEW COMMENT -->
              {% if messages %}
              {% for error in messages%}
              {% with error.extra_tags|stringformat:'s' as tag %}
              {% with message.id|stringformat:'s' as id %}
              {% if tag == id %}
              <p class="error">{{ error }}</p>
              {% endif %}
              {% endwith %}
              {% endwith %}
              {% endfor %}
              {% endif %}
              <div class="form-group">
                <textarea rows="1" cols="60" name="comment" class="comment-input"></textarea>
                <button class="btn btn--green submit" name="wall_posts" value="comment_submit" type="submit">Comment</button>
              </div>
            </form>
          </div>
          <!-- END COMMENT FORM -->
          </div>
      </div>
      <!-- END MESSAGE-GROUP          -->
          {% endfor %}
          {% endif %}
      </div>

  </section>
  <!-- /container -->

</body>

</html>