CodingKatz/CodingKatz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

app_name="CodingKatz"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.LogReg.urls', namespace="LogReg")),
    url(r'^', include('apps.Wall.urls', namespace="Wall")),
    url(r'^', include('apps.User.urls', namespace="User")),
]

CodingKatz/apps/LogReg/urls.py
from django.conf.urls import url
from . import views

app_name="LogReg"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    # url(r'^1$', views.index1, name="index1"),
    # url(r'^2$', views.index2, name="index2"),
    # url(r'^3$', views.index3, name="index3"),
    url(r'^login', views.log_reg, name="login"),
    url(r'^register', views.log_reg, name="register"),
    url(r'^logout', views.logout, name="logout"),
]

CodingKatz/apps/LogReg/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import bcrypt, re

EMAILREG = re.compile(r'[a-zA-Z0-9.-_+]+@[a-zA-Z0-9.-_]+\.[a-zA-Z]*$')

class userDBManager(models.Manager):
    def check_create(self, data):
        errors = []
        if len(data['first_name']) < 2:
            errors.append(['first_name', "First name must be at least two characters in length."])
        if len(data['last_name']) < 2:
            errors.append(['last_name', "Last name must be at least two characters in length."])
        if not re.match(EMAILREG, data['email']):
            errors.append(['email', "Email must be a valid email address."])
        if data['password'] != data['confirmPassword']:
            errors.append(['password', 'Password must match password confirmation. Please try again.'])
        if (len(data['password']) < 8) or (len(data['confirmPassword']) < 8):
            errors.append(['password', 'Password must be at least 8 characters.'])
        if errors:
            return [False, errors]
        else:
            user_check = userDB.objects.filter(email=data['email'])
            if user_check:
                #CONFIRM ERROR MESSAGE IS SECURE
                errors.append(['user_check', 'Unable to register, please use alternate email.'])
                return [False, errors]
            newUser = userDB(first_name=data['first_name'], last_name=data['last_name'], email=data['email'])
            hashed_pass = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt()).decode('utf-8')
            newUser.password = hashed_pass
            newUser.save()
            return [True, newUser]

    def check_login(self, data):
        errors = []
        if not re.match(EMAILREG, data['email']):
            errors.append(['email', "Email must be a valid email address."])
        if len(data['email']) < 5:
            errors.append(['email', 'Email must be entered.'])
        if errors:
            return [False, errors]
        else:
            check_user = userDB.objects.filter(email=data['email'])
            if not check_user:
                errors.append(['login', "Email or password not correct.  Please try again."])
            if not bcrypt.checkpw(data['password'].encode(), check_user[0].password.encode()):
                errors.append(['login', "Email or password not correct.  Please try again."])
            if errors:
                return [False, errors]
            else:
                user = check_user[0]
                print (user)
                return [True, user]

    #edit user info
    def check_info_edit(self, data, user_id):
        print (data)
        errors = []
        if len(data['first_name']) < 2:
            errors.append(['first_name', "First name must be at least two characters in length."])
        if len(data['last_name']) < 2:
            errors.append(['last_name', "Last name must be at least two characters in length."])
        if not re.match(EMAILREG, data['email']):
            errors.append(['email', "Email must be a valid email address."])
        if len(data['password']) < 8:
            errors.append(['password', 'Password must be at least 8 characters.'])
        if len(data['confirmPassword']) < 8 or data['confirmPassword'] != data['password']:
            errors.append(['confirmPassword', 'Password confirmation must be entered and match password.'])
        if errors:
            return [False, errors]
        else:
            edit_user = userDB.objects.get(id=user_id)
            if data['email'] != edit_user.email:
                user_email_check = userDB.objects.filter(email=data['email'])
                if user_email_check:
                    #CONFIRM SECURITY OF MESSAGE
                    errors.append(['user_email_check', 'Unable to edit, please use alternate information.'])
                    return [False, errors]
            edit_user.first_name = data['first_name']
            edit_user.last_name = data['last_name']
            edit_user.email = data['email']
            hashed_pass = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            edit_user.password = hashed_pass
            edit_user.save()
            return [True, edit_user]

# Create your models here.
class userDB(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return 'ID: %s | Name: %s %s | Email: %s' % (self.id, self.first_name, self.last_name, self.email)
    objects = userDBManager()

CodingKatz/apps/LogReg/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import userDB

def index(request):
    return render(request, 'LogReg/index.html')

def log_reg(request):
    if request.method == "POST":
        # print ('attempt: ', request.POST['attempt'])
        print ('POST: ', request.POST)
        if request.POST['attempt'] == "register":
            request.session['attempt'] = 'register'
            response = userDB.objects.check_create(request.POST)
        elif request.POST['attempt'] == 'login':
            request.session['attempt'] = 'login'
            response = userDB.objects.check_login(request.POST)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
            return redirect('LogReg:index')
        else:
            request.session['user'] = {
                "first_name": response[1].first_name,
                "last_name": response[1].last_name,
                "id": response[1].id,
            }
        return redirect('Wall:wall')
    return redirect('LogReg:index')

def logout(request):
    request.session.clear()
    return redirect('LogReg:index')
# Create your views here.

CodingKatz/apps/LogReg/templates/LogReg/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'LogReg/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'LogReg/css/style.css' %}">
  <title>Code Social</title>
</head>
<body class="container">
  <div class="overlay"></div>
  <header class="header">
    <div class="header__right">
      <form class="header__form form" action="{% url 'LogReg:login' %}" method="POST">
        {% csrf_token %}
        <div class="form__group ">
          <input name="email" type="email" placeholder="Email" class="form__input">
          <label class="form__label" for="email">Email</label>
        </div>
        <div class="form__group ">
          <input name="password" type="password" placeholder="Password" class="form__input">
          <label class="form__label" for="password">Password</label>
        </div>
        <div class="form__group ">
          <button type="submit" class="btn btn--blue" name="attempt" value="login">Sign in</button>
        </div>
      </form>
    </div>
          {% if messages and request.session.attempt == 'login' %} 
          <ul>
             {% for message in messages %}
             <li class="navError">-{{ message }}</li>
             {% endfor %}
          </ul>
          {% endif %}
  </header>


  <section class="content">
    <div class="register">
      <div class="register__form">
        <form action="{% url 'LogReg:register' %}" method="POST" class="form">
          {% csrf_token %}
          <div class="form-header">
            <h2 class="heading-secondary">New here? Please register and join us!</h2>
          </div>
          <div class="form__group">
            <input id="inputFirstName" type="text" name="first_name" placeholder="First Name" class="form__input" required>
            <label class="form__label" for="inputFirstName">First Name</label>
          </div>
          <div class="form__group">
            <input id="inputLastName" type="text" name="last_name" placeholder="Last Name" class="form__input" required>
            <label class="form__label" for="inputLastName">Last Name</label>
          </div>
          <div class="form__group">
            <input id="inputEmail" type="email" name="email" class="form__input" placeholder="Email address" required>
            <label class="form__label" for="inputEmail">Email address</label>
          </div>
          <div class="form__group">
            <input type="password" name="password" id="inputPassword" class="form__input" placeholder="Password" required>
            <label class="form__label" for="inputPassword">Password</label>
          </div>
          <div class="form__group">
            <input type="password" name="confirmPassword" id="inputConfirmPassword" class="form__input" placeholder="confirm password entry" required>
            <label class="form__label" for="inputConfirmPassword">Confirm Password:</label>
          </div>
          <div class="form__group">
            {% if messages and request.session.attempt == 'register' %} {% for message in messages %}
            <p class="navError">{{ message }}</p>
            {% endfor %} {% endif %}
          </div>
          <div class="form__group">
            <button type="submit" class="btn btn--blue" name="attempt" value="register">Register</button>
          </div>
        </form>
      </div>

      <div class="intro">
        <div class="intro__text">
          <h1>Code Social</h1>
          <p>A place for Coding Dojo students past and present to socialize and talk about anything and everything, including code.</p>
        </div>
      </div>

    </div>
  </section>

</body>
</html>