CodingKatz/CodingKatz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

app_name="CodingKatz"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.LogReg.urls', namespace="LogReg")),
    url(r'^', include('apps.Wall.urls', namespace="Wall")),
    url(r'^', include('apps.User.urls', namespace="User")),
]

CodingKatz/apps/LogReg/urls.py
from django.conf.urls import url
from . import views

app_name="LogReg"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    # url(r'^1$', views.index1, name="index1"),
    # url(r'^2$', views.index2, name="index2"),
    # url(r'^3$', views.index3, name="index3"),
    url(r'^login', views.log_reg, name="login"),
    url(r'^register', views.log_reg, name="register"),
    url(r'^logout', views.logout, name="logout"),
]

CodingKatz/apps/User/urls.py
from django.conf.urls import url
from . import views

app_name="User"

urlpatterns = [
    url(r'^profile', views.profile, name="profile"),
    url(r'^edit', views.edit, name="edit"),
    url(r'^delete', views.delete, name="delete"),
    url(r'^note/(?P<user_id>\d+)/$', views.note, name="note"),
    url(r'^userComment/(?P<user_id>\d+)/(?P<message_id>\d+)*$', views.comment, name='userComment'),
    url(r'^userDeleteMessage/(?P<user_id>\d+)/(?P<message_id>\d+)/$', views.deleteMessage, name="userDeleteMessage"),
    url(r'^userDeleteComment/(?P<user_id>\d+)/(?P<comment_id>\d+)/$', views.deleteComment, name="userDeleteComment"),
    url(r'^users/show/(?P<user_id>\d+)/$', views.show_user, name='show_user'),
]

CodingKatz/apps/Wall/urls.py
from django.conf.urls import url
from . import views

app_name="Wall"

urlpatterns = [
    url(r'^wall', views.wall, name="wall"),
    url(r'^message', views.message, name="message"),
    url(r'^comment/(?P<message_id>\d+)*$', views.comment, name='comment'),
    url(r'^deleteMessage/(?P<message_id>\d+)/$', views.deleteMessage, name="deleteMessage"),
    url(r'^deleteComment/(?P<comment_id>\d+)/$', views.deleteComment, name="deleteComment"),
    # url(r'^users/show/(?P<user_id>\d+)/$', views.show_user, name='show_user'),
]

CodingKatz/apps/User/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from ..LogReg.models import userDB
# Create your models here.

class noteManager(models.Manager):
    def note_check(self, data, author, user_id):
        errors = []
        if len(data['note'])  < 1:
            errors.append(['note', 'Note must be entered.'])

        if errors:
            return [False, errors]
        else:
            recipient = userDB.objects.get(id = user_id)
            newNote = Note.objects.create(note=data['note'], author=author, recipient=recipient)
            return [True]

class Note(models.Model):
    note = models.TextField()
    author = models.ForeignKey(userDB, related_name='note_author', on_delete=models.PROTECT)
    recipient = models.ForeignKey(userDB, related_name='note_recipient', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = noteManager()

CodingKatz/apps/User/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from itertools import chain
from operator import attrgetter
from ..LogReg.models import userDB
from ..Wall.models import Message, Comment
from .models import Note

def profile(request):
    #Confirm user id is logged in to view that page
    if "user" in request.session:
    #User information in session and can be displayed on the page through the template
        context = {
            'user': userDB.objects.get(id=request.session['user']['id']),
        }
    #Display user page
        return render(request, 'User/profile.html', context)
    return redirect('LogReg:index')

#validates information and updates user accordingly
def edit(request):
    print(request)
    #Content from edit form
    if request.method == 'POST':
    #Validate content from form
        response = userDB.objects.check_info_edit(request.POST, request.session['user']['id'])
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1])
        #Update session user
        request.session['user'] = {
            "first_name": response[1].first_name,
            "last_name": response[1].last_name,
            "id": response[1].id,
        }
    #Redirect user to user profile page
    return redirect('User:profile')

def delete(request):
    #Confirm user wants to delete their account

    #Consider whether to Cascade delete user's information, messages, and comments from the database

    #Potential for 'recover account' for users which will bring back all their data

    #Return former user to landing page
    return redirect('LogReg:index')

def note(request, user_id):
    #Content from message
    #Validate content
    #Put message in database
    #Return message to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Note.objects.note_check(request.POST, author, user_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags='message')
    user = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=user).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=user).order_by('id').reverse()

    all_user_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': user,
        'all_correspondence': all_user_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

def comment(request, message_id, user_id):
    #Content from comment
    #Validate content
    #Put comment in database
    #Return comment to page for display
    if request.method == "POST":
        author = userDB.objects.get(id=request.session['user']['id'])
        response = Comment.objects.comment_check(request.POST, author, message_id)
        if not response[0]:
            for error in response[1]:
                messages.error(request, error[1], extra_tags = message_id)
    user = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=user).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=user).order_by('id').reverse()

    all_user_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': user,
        'all_correspondence': all_user_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

def deleteMessage(request, message_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete message from database

    #Return user to page through redirect
    return redirect('User:user')

def deleteComment(request, comment_id):
    #Figure out how to do confirmation for deletion (possibly pop up alert)

    #Delete comment from database

    #Return user to page through redirect
    return redirect('User:user')

#display user page with their messages and comments
def show_user(request, user_id):
    recipient = userDB.objects.get(id = user_id)
    all_messages = Message.objects.filter(author=recipient).order_by('id').reverse()

    all_notes =  Note.objects.filter(recipient=recipient).order_by('id').reverse()

    all_recipient_correspondence = sorted(
    chain(all_notes, all_messages),
    key=attrgetter('created_at'))

    context = {
        'user': recipient,
        'all_correspondence': all_recipient_correspondence,
        'comments': Comment.objects.all().order_by('id')
    }
    return render(request, 'User/user.html', context)

# Create your views here.

CodingKatz/apps/User/templates/User/profile.html
<!DOCTYPE html>
<html>
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <!-- css stylesheets -->
    <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
    <title>{{user.first_name}}'s Profile - Edit</title>
  </head>
  <body class="grid">
    <div class="overlay"></div>
    <header class="header">
      <nav class="navbar">
        <ul class="top-nav">         
          <li class="top-nav__item">
            <a href="{% url 'Wall:wall' %}"" class="top-nav__link"">Community Wall</a>
          </li>
          <li class="top-nav__item">
            <a href="{% url 'User:show_user' user.id %}" class="top-nav__link">My wall</a>
          </li>
          <li class="top-nav__item">
            <a href="{% url 'LogReg:logout' %}"" class="top-nav__link"">Logout</a>
          </li>
        </ul>
      </nav>
      <div class="header__greeting">
        <h1>{{user.first_name}}'{% if user.first_name|last != "s" %}s {% endif %} Profile - Edit</h1>
      </div>
    </header>


    <section class="content">
      <div class="user-edit">
        <div class="user-edit__form">
          <form action="{% url 'User:edit' %}" method="POST" class="form">
            {% csrf_token %}
            <div class="form-header">
              <h2>Edit Your Info</h2>
            </div>
            <div class="form__group">
              <input id="first_name" type="text" name="first_name" value="{{user.first_name}}" class="form__input" autofocus>
              <label class="form__label" for="first_name">First Name</label>
            </div>
            <div class="form__group">
              <input id="last_name" type="text" name="last_name" value="{{user.last_name}}" class="form__input">
              <label class="form__label" for="last_name">Last Name</label>
            </div>
            <div class="form__group">
              <input id="email" type="email" name="email" class="form__input" value="{{user.email}}">
              <label class="form__label" for="email">Email address</label>
            </div>
            <div class="form__group">
              <input type="password" name="password" id="password" class="form__input" placeholder="Password">
              <label class="form__label" for="password">Password</label>
            </div>
            <div class="form__group">
              <input type="password" name="confirmPassword" id="confirmPassword" class="form__input" placeholder="confirm password entry">
              <label class="form__label" for="confirmPassword">Confirm Password:</label>
            </div>
            <div class="form__group">
              {% if messages %}
              {% for message in messages%}
              <p class="error">{{ message }}</p>
              {% endfor %}
              {% endif %}
            </div>
            <div class="form__group">
              <button class="btn btn--blue" type="submit" >Submit</button>
            </div>
          </form>

        </div>
      </div>

    </section> <!-- /container -->

  </body>
</html>

CodingKatz/apps/User/templates/User/user.html
<!DOCTYPE html>
<html>
{% load staticfiles %} 

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

  <!-- css stylesheets -->
  <link rel="stylesheet" href="{% static 'user/css/style.css' %}">
  <title>{{ user.first_name }}'s Wall</title>
</head>

<body class="grid">
  <div class="overlay"></div>
  <header class="header">
    <nav class="navbar">
      <ul class="top-nav">
        <li class="top-nav__item">
          <a href="{% url 'Wall:wall' %}" class="top-nav__link">Community Wall</a>
        </li>
        <li class="top-nav__item">
          <a href="{% url 'User:profile' %}" class="top-nav__link"> Edit Profile</a>
        </li>
        <li class="top-nav__item">
          <a href="{% url 'LogReg:logout' %}" class="top-nav__link">Logout</a>
        </li>
      </ul>
    </nav>
    <div class="header__greeting">
      <h1>{% if "user" in request.session %}
        {{ user.first_name }}'{% if user.first_name|last != "s" %}s
        {% endif %}
         Wall
        {% endif %}</h1>
      <h4>
        Member Since:
        <!-- time is showing 3 hours ahead but this fix does not work -->
        {% load tz %}
        {% localtime on %}
        {{user.created_at}}
        {% endlocaltime %}
      </h4>
    </div>
  </header>

  <div id="main" class="content">

    <section id="note" class="form">
      <!-- user info then notes and messages -->
      <h2>Leave a note for {{user.first_name}}</h2>
      <form action="{% url 'User:note' user.id %}" method="post">
      {% csrf_token %}
      <fieldset>
        <div class="form-group">
          <label class="flash_messages">
            {% if messages %}
            {% for message in messages %}
            {% if message.extra_tags == 'message' %}
            <p class="error">{{ message }}</p>
            {% endif %}
            {% endfor %}
            {% endif %}
          </label>            
        </div>
        <div class="form-group">
          <textarea name="note" rows="4" class="message-input"></textarea>
          <button class="btn btn--blue submit" name="button" value="note_submit" type="submit">Submit</button>
        </div>
      </fieldset>
        </form>
        
        <div class="notes">
          {% for message in all_correspondence %}
          <div class="note-group">
            <h5><a href="{% url 'User:show_user' message.author.id %}" class="notes__link">{{message.author.first_name}} {{message.author.last_name}}</a>  - {{message.created_at|timesince}} ago</h5>
            {% if message.message %}
            <p class="notes">{{ message.message }}</p>
            {% endif %}
            {% if message.note %}
            <p class="notes">{{ message.note }}</p>
            {% endif %}
            
            <div class="comments">
              <!-- SINGLE COMMENT SECTION -->
              <div class="comment">
                {% if comments %}
                <ul>
                  {% for comment in comments %} {% if message.id == comment.message.id %}
                  <li></li>
                  <h5>
                    <a href="{% url 'User:show_user' comment.author.id %}" class="comments__link">{{comment.author.first_name}} {{comment.author.last_name}}</a> - {{comment.created_at|timesince}} ago</h5>
                    {{ comment.comment }}</li>
                    {% endif %} {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="comment-form">
                  <h6 class="comment_label">Post a comment</h6>
                  <form action="{% url 'User:userComment' user_id=user.id message_id=message.id %}" method="post">
                    {% csrf_token %}
                    <div class="flash_messages">
                      {% if messages %}
                      {% for error in messages%}
                      {% with error.extra_tags|stringformat:'s' as tag %}
                      {% with message.id|stringformat:'s' as id %}
                      {% if tag == id %}
                      <p class="error">{{ error }}</p>
                      {% endif %}
                      {% endwith %}
                      {% endwith %}
                      {% endfor %}
                      {% endif %}
                    </div>
                    <div class="form-group">
                      <textarea name="comment" class="comment-input" rows="1" cols="60"></textarea>
                      <button class="btn btn--green submit" name="wall_posts" value="comment_submit" type="submit">Submit</button>
                    </div>
                  </form>
                </div>
                <!-- CREATE ANCHOR TAG SO THAT WHEN PAGE REFRESHES FOR COMMENT OR ERROR THE PAGE LOADS AT THIS PARTICULAR MESSAGE AND COMMENT BOX -->
                
              </div>
            </div>
            {% endfor %}
          </div>
        </section>
        </body>
        
        </html>
        